"""Initial schema

Revision ID: 3dc9e05d5bda
Revises: 
Create Date: 2026-07-14 10:05:21.707255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dc9e05d5bda'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hcp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=False),
    sa.Column('hospital', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('preferred_products', sa.JSON(), nullable=False),
    sa.Column('relationship_score', sa.Float(), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_hcp_id'), 'hcp', ['id'], unique=False)
    op.create_table('interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hcp_id', sa.Integer(), nullable=False),
    sa.Column('rep_id', sa.String(length=100), nullable=False),
    sa.Column('interaction_date', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('discussion_topics', sa.JSON(), nullable=False),
    sa.Column('products_discussed', sa.JSON(), nullable=False),
    sa.Column('samples_distributed', sa.JSON(), nullable=False),
    sa.Column('competitors_mentioned', sa.JSON(), nullable=False),
    sa.Column('objections', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'SKEPTICAL', 'NEGATIVE', name='sentimentenum'), nullable=False),
    sa.Column('sentiment_confidence', sa.Float(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=False),
    sa.Column('raw_transcript', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hcp_id'], ['hcp.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_id'), 'interaction', ['id'], unique=False)
    op.create_table('agent_run_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('output_payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_log_id'), 'agent_run_log', ['id'], unique=False)
    op.create_table('follow_up',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interaction_id', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_up_id'), 'follow_up', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follow_up_id'), table_name='follow_up')
    op.drop_table('follow_up')
    op.drop_index(op.f('ix_agent_run_log_id'), table_name='agent_run_log')
    op.drop_table('agent_run_log')
    op.drop_index(op.f('ix_interaction_id'), table_name='interaction')
    op.drop_table('interaction')
    op.drop_index(op.f('ix_hcp_id'), table_name='hcp')
    op.drop_table('hcp')
    # ### end Alembic commands ###
